[package]
name = "attested-tls-proxy"
version = "1.1.1"
edition = "2024"
license = "MIT"
readme = "../../README.md"
description = "An HTTP attested TLS proxy server and client for secure communication with CVM services"
repository = "https://github.com/flashbots/attested-tls-proxy"
keywords = ["attested-TLS", "CVM", "TDX"]

[dependencies]
attested-tls = { path = "../attested-tls", default-features = false }
tokio = { workspace = true, features = ["full"] }
tokio-rustls = { workspace = true, features = ["aws_lc_rs"] }
thiserror.workspace = true
clap.workspace = true
rustls-pemfile.workspace = true
anyhow.workspace = true
pem-rfc7468 = { version = "0.7.0", features = ["std"] }
hyper = { workspace = true, features = ["server", "http2"] }
h2.workspace = true
hyper-util = { workspace = true, features = ["tokio"] }
http-body-util.workspace = true
bytes.workspace = true
http.workspace = true
serde_json.workspace = true
hex = "0.4.3"
serde = "1.0.228"
reqwest = { version = "0.13.4", default-features = false, features = [
  "rustls-no-provider",
] }
tracing.workspace = true
tracing-subscriber.workspace = true
axum = "0.8.8"
tower-http = { version = "0.6.7", features = ["fs"] }
pin-project-lite = "0.2.16"
pccs = { git = "https://github.com/flashbots/attested-tls", branch = "main" }

[dev-dependencies]
rcgen.workspace = true
tempfile.workspace = true
tdx-quote = { version = "0.0.5", features = ["mock"] }
attested-tls = { path = "../attested-tls", features = ["test-helpers", "mock"] }
jsonrpsee = { version = "0.26.0", features = ["server"] }

[features]
default = []

# Adds support for Microsoft Azure attestation generation and verification
azure = ["attested-tls/azure"]

[package.metadata.deb]
maintainer = "Flashbots Team <devops+ci@flashbots.net>"
depends = "$auto"
section = "network"
priority = "optional"
maintainer-scripts = "../../pkg/debian"
assets = [
    [
        # cargo-deb resolves this prefix to the workspace target and selected profile.
        "target/release/attested-tls-proxy",
        "usr/bin/",
        "755",
    ],
    [
        "../../LICENSE",
        "usr/share/doc/attested-tls-proxy/",
        "644",
    ],
]
systemd-units = { enable = false, start = false, unit-name = "attested-tls-proxy" }
